# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-20 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 5, 20, 16, 57, 53, 779562, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
